#!/bin/bash

if [ "$(id -u)" = 0 ]; then
    echo "You're root! Run script as user" && exit 1
fi

# Call with arguments (path, line to add)
function add_to_file() {
    touch "$1"
    grep -qxF "$2" "$1" || echo "$2" >>"$1"
  }

#==============================================================================
# Set host name
#==============================================================================
read -rp "What is this computer's name? [$HOSTNAME] " hostname
if [[ ! -z "$hostname" ]]; then
    hostnamectl set-hostname "$hostname"
fi

#==============================================================================
# Gnome desktop settings
#==============================================================================
idle_delay=2400
title_bar_buttons_on="true"
clock_show_date="true"
capslock_delete="true"
night_light="true"

gsettings set org.gnome.desktop.session \
    idle-delay $idle_delay

if [[ "${title_bar_buttons_on}" == "true" ]]; then
    gsettings set org.gnome.desktop.wm.preferences \
        button-layout 'appmenu:minimize,maximize,close'
fi

if [[ "${clock_show_date}" == "true" ]]; then
    gsettings set org.gnome.desktop.interface \
        clock-show-date true
fi

if [[ "${capslock_delete}" == "true" ]]; then
    gsettings set org.gnome.desktop.input-sources \
        xkb-options "['caps:backspace', 'terminate:ctrl_alt_bksp']"
fi

if [[ "${night_light}" == "true" ]]; then
    gsettings set org.gnome.settings-daemon.plugins.color \
        night-light-enabled true
fi

#==============================================================================
# Pulse audio settings for better sound quality
#==============================================================================
sudo sed -i "s/; default-sample-format = s16le/default-sample-format = s32le/g" /etc/pulse/daemon.conf
sudo sed -i "s/; resample-method = speex-float-1/resample-method = speex-float-10/g" /etc/pulse/daemon.conf
sudo sed -i "s/; avoid-resampling = false/avoid-resampling = true/g" /etc/pulse/daemon.conf


#==============================================================================
# Font settings for subpixel rendering
#==============================================================================
RESOLUTION=$(xrandr | grep '*' | awk -Fx '{ gsub(/ /,"");print $1 }')

if [[ $RESOLUTION -gt 1920 ]]; then
    echo "Vertical resolution $RESOLUTION is greater than 1920, skipping sub pixel rendering"
else
    echo "Vertical resolution $RESOLUTION is less than or equal to 1920, activating subpixel rendering for fonts without fontconfig support and rgba antialiasing"

    add_to_file "$HOME/.Xresources" "Xft.lcdfilter: lcddefault"
    dconf write /org/gnome/settings-daemon/plugins/xsettings/antialiasing "'rgba'"
fi

#==============================================================================
# Add settings to config files 
#==============================================================================

# alias
add_to_file "$HOME/.bashrc" \
'alias ls="ls -ltha --color --group-directories-first"
alias tree="tree -Catr --noreport --dirsfirst --filelimit 100"
alias diff="diff -u --color=always"'

# nnn
add_to_file "$HOME/.bashrc" 'alias nnn="nnn -xe"'
add_to_file "$HOME/.bashrc" "export NNN_TRASH=1"
add_to_file "$HOME/.bashrc" 'export NNN_PLUG="p:addtoplaylist;f:fzcd"' 
add_to_file "$HOME/.bashrc" "export NNN_BMS='d:~/Documents;D:~/Downloads;p:~/Pictures;v:~/Videos;m:~/Music;h:~/'"

# must add $HOME/.deno/bin:$HOME/Documents/scripts:$HOME/.npm-global/bin:$PATH
# export YTFZF_PREF="bestvideo[height<=?1080]+bestaudio/best"
# export FZF_DEFAULT_COMMAND='find . -path './.git' -prune -o -print'
# clip() { xclip -sel clip -rmlastnl; }
# stty -ixon # disable terminal flow control to free ctrl-s for shortcut

#===============================================================================
# Increase inotify watchers for watching large numbers of files, default is 8192
#
# curl -s https://raw.githubusercontent.com/fatso83/dotfiles/master/utils/scripts/inotify-consumers | bash
#===============================================================================
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

cat <<EOL
=================================================================
Gnome:    settings  > details > choose default applications
          network   > wired   > connect automatically
          software  > install 'Hide Top Bar'

flatpak run org.mozilla.firefox https://addons.mozilla.org/en-GB/firefox/addon/privacy-badger17/ \
https://addons.mozilla.org/en-GB/firefox/addon/ublock-origin/ \
https://addons.mozilla.org/en-US/firefox/addon/vimium-ff/

Firefox:  Preferences > Network Settings > Enable DNS over HTTPS
          about:config network.security.esni.enabled
          (test with https://www.cloudflare.com/ssl/encrypted-sni/)

          Privacy & Security > HTTPS-Only Mode > Enable HTTPS-Only Mode in all windows

NPM: use your home directory for global packages
--------------------------------------------------------
mkdir "$HOME/.npm-global"
npm config set prefix "$HOME/.npm-global"

ytfzf: helps you find Youtube videos (without API) and opens/downloads them using mpv/youtube-dl
------------------------------------------------------------------------------------------------
git clone https://github.com/pystardust/ytfzf
cd ytfzf
sudo make install

Fix Visual Studio Code keyboard input on RHEL 8 clones
------------------------------------------------------
add alias code="GTK_IM_MODULE=ibus code" to .bashrc
go to terminal type 'ibus-setup'
go to Emoji tab, press the '...' next to Emoji choice to get 'select keyboard shortcut for switching' window
use the delete button to delete the shortcut and leave nothing there, press OK
Close

Please reboot (or things may not work as expected)
=================================================================
EOL
